# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02e13072539e51ba1de6d9516ab415a5e52a5573512ef31d81010f1c8ee68a96dd48c3a68f131eebab06649a9bb4c7f54773ab2a671e74d048fbe6600c6c81a9

test:
  secret_key_base: 6bfc4a51d9ccbb784ac6fa0a20f29e73cf6d7148eaadd1310a078887272bd9cab5896586194e319f55afd3c5abd10ee82a58670dcec4dab896c83629bc4db68b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
